:doctype: book
:nofooter:

= Maria Zhirko

==== Software Engineer
Location | Minsk, Belarus +
Phone Number | +375(29)3778667 +
Gmail | \mzhirko@gmail.com +
Github | https://github.com/mzhirko[mzhirko] 

[#it-skills]
=== IT Skills
'''
==== Software Development:
*Programming languages:* Python, C++, Java, SQL, Bash; +
*Frameworks:* numpy, pandas, matplotlib, OpenCV, Keras; +
*Tools:* Docker, Docker Compose, CI/CD, Git, Gradle, MySQL.

==== Operating Systems:
*Linux:* Ubuntu, Debian, Mint, Arch; +
*Other:* Windows WSL, FreeBSD, MacOS (GNU core utils).

[#projects]
=== Projects
'''
==== *Automated Natural Language Dictionary System*
Project link: https://github.com/mzhirko/word-analyser[https://github.com/mzhirko/word-analyser]:::
An application for displaying dictionary with a list of words ordered alphabetically which includes only lexemes with additionally formed information about the place and role of a given word in a sentence. +
Programming language: Python; +
Tools: https://api.ispras.ru/texterra/v1/docs[Texterra REST].

==== *Parking lot control system:*
Project link: https://github.com/mzhirko/convenient-parking[https://github.com/mzhirko/convenient-parking]:::
An application for recognizing free parking spaces using M-RCNN. The user provides photo or video data to process and find free parking spaces on it. Containerized in Docker. +
Programming language: Python; +
Tools: Docker, Keras, Tensorflow v.1, OpenCV.

==== *Image compression tool:* 
Project link: https://github.com/mzhirko/image-compressor[https://github.com/mzhirko/image-compressor]:::
An application for compressing images using the conception of recirculation neural network with adaptive learning step and normalization of weights. +
Programming language: Python; +
Tools: matplotlib, numpy.


==== *Sequence prediction tool:* 
Project link: https://github.com/mzhirko/sequence-prediction[https://github.com/mzhirko/sequence-prediction]:::
Implementation of an Elman network model with a linear activation function. +
Programming language: Python; +
Tools: numpy.

==== *Object oriented analysis and design:*
Project link: https://github.com/mzhirko/amusement-park[https://github.com/mzhirko/amusement-park]:::
Practicing skills of developing documentation as a code. The conception of a project is to show documentation writing skills, based on knowledge of certain projecting patterns such as KISS, SOLID, etc. The advantage of writing documentation as code is in its convenience to develop documents and control changes. +
Tools: Asciidoc, PlantUML.

==== *Visualized minimum cut algorithm:* 
Project link: https://github.com/mzhirko/minimum-cut-of-an-undirected-graph[https://github.com/mzhirko/minimum-cut-of-an-undirected-graph]:::
This project demonstrates the work of the Stoer-Wagner algorithm, which is used to find a minimum cut of a graph. The demonstration is visualized with the Graphviz tool. +
Programming language: C++; +
Tools: Graphviz.

==== *Java Toolbars:*
Project link: https://github.com/mzhirko/javafx-basics[https://github.com/mzhirko/javafx-basics]:::
Project with a configured CI. Shows different visuals made by using JavaFX lib. +
Programming language: Java; +
Tools: Gradle, Github CI.

[#language-skills]
=== Language Skills
'''
*English:* B2-C1; +
*German:* A2-B1; +
*Belarusian:* Native; +
*Russian:* Native.

[#work-experience]
=== Education
'''
2022  ~June~:::  
*Belarusian State University of Informatics and Radioelectronics;* +
Faculty: Faculty of Information Technologies and Control; +
Degree:  Artificial Intelligence. +
2018  ~May~::: 
*Minsk Gymnasium 29;* +
Educational focus: English and Mathematics.

[#driving-license]
=== Driving license

[#interests]
=== Personal Interests
'''
*Hobbies:* +
traveling, driving, drawing, art, self-education, walking, baking, communication, electronics, classical literature & music.

[#prospects]
=== Prospects
'''
Grow and develop soft and hard skills to correspond to surrounding requirements; +
Take an advantage of doing hard tasks to get higher on the proficiency scale; +
Passion to work with high-loaded, scalable, distributed, real-time information processing systems; +
Desire to improve in the scientific field.
